services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=pytest
      - POSTGRES_USER=pytest
      - POSTGRES_PASSWORD=pytest
    command: |
      -c ssl=on
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
  test:
    build:
      context: .
      dockerfile: ./tests/integration/Dockerfile
